name: Composer Dependency Updates

on:
  pull_request:
    paths:
      - 'composer.json'
      - 'composer.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  composer-diff:
    name: Composer Lock Diff
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write # needed for sticky-pull-request-comment to post/update PR comments
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Required for IonBazan/composer-diff-action
          # Do not store git credentials in .git -> could be leaked/exposed by infected/malicious action.
          persist-credentials: false

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Audit Composer packages
        run: composer audit --locked --abandoned=report

      - name: Generate composer.lock diff
        id: composer-diff
        uses: IonBazan/composer-diff-action@e2022e8718d05cc6e4e5990a06fc928c75837f76 # v2.0.0

      - name: Post diff as sticky comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        # An empty diff result will break this action.
        if: ${{ steps.composer-diff.outputs.composer_diff_exit_code != 0 }}
        with:
          header: composer-diff # Creates a collapsed comment with the report
          message: |
            <details>
            <summary>Composer package changes</summary>

              ${{ steps.composer-diff.outputs.composer_diff }}

            </details>
