name: Pull Request Tests

on:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        # TODO: Add 8.0 when released.
        deployer: ['^7.3', '^7.4', '^7.5']
        include:
          - name: Deployer ${{ matrix.deployer }} on PHP ${{ matrix.php }}
      fail-fast: false

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
