name: Tests

on:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4', '8.5' ]
        deployer: [ '7.3', '7.4', '7.5', '8.0' ]
        exclude:
          - php: '8.2'
            deployer: '8.0'
      fail-fast: false
    name: Tests for Deployer ${{ matrix.deployer }} on PHP ${{ matrix.php }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Do not store git credentials in .git -> could be leaked/exposed by infected/malicious action.
          persist-credentials: false

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      # Install dependencies with caching
      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          composer-options: '--prefer-dist --no-progress'

      # Install specific Deployer version
      - name: Install Deployer version
        # Install latest patch of the specified version.
        env:
          DEPLOYER_VERSION: ${{ matrix.deployer }}
        run: composer require --no-update deployer/deployer:"${DEPLOYER_VERSION}.*"

      # Run PHPStan so we check compatibility with the specified Deployer version.
      - name: Run PHPStan
        run: composer run-script phpstan

      - name: Run PHPUnit tests
        run: composer run-script tests
